language: php

php:
  - 5.3
  - 5.3.2
  - 5.4

before_install:
  - cd ~/builds
  - git clone git://github.com/laravel/laravel.git
  - mv ./Anahkiasen/former ./laravel/bundles/former
  - echo "<?php return array('former' => array('auto' => true));" > ./laravel/application/bundles.php
  - cd ./laravel

script: "php artisan test former"